# Generated by Django 5.0.1 on 2026-04-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="period",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.class"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.section"
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.attendancestatus",
            ),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="absent_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="attendance_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="excused_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="late_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="present_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="total_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancesummary",
            name="year",
            field=models.IntegerField(),
        ),
    ]
