# Generated by Django 5.0.1 on 2026-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
